### ISSUE TITLE
When running usage example,  'I2C' is not defined

### ISSUE THREAD

**Issue by itsjesseyo** [khoulihan/micropython-tmp102#1]
the second line under usage returns this error:
NameError: name 'I2C' is not defined

when I do...
from machine import I2C, the error becomes:
AttributeError: type object 'I2C' has no attribute 'MASTER'

Read your post in the forums. Thanks for putting real effort into this. Sorry I'm a little too newb at micropython to be of much help.

**Comment by khoulihan** [comment]
Thanks for the report, and sorry about the slow response, I don't check in on github very often!

The `machine` module didn't exist when I wrote this code, so the I2C class that has to be used is the one from the `pyb` module:

`from pyb import I2C`

However, I've just committed a change that should make it work for an I2C object from either module. I also updated the docs to hopefully clarify that.
